<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="" tests="6" assertions="4" errors="2" warnings="1" failures="0" skipped="0" time="0.017630">
    <testsuite name="App" tests="5" assertions="4" errors="2" warnings="0" failures="0" skipped="0" time="0.017485">
      <testsuite name="ExampleDatabaseTest" file="/var/www/html/ardis/tests/database/ExampleDatabaseTest.php" tests="2" assertions="0" errors="2" warnings="0" failures="0" skipped="0" time="0.014169">
        <testcase name="testModelFindAll" class="ExampleDatabaseTest" classname="ExampleDatabaseTest" file="/var/www/html/ardis/tests/database/ExampleDatabaseTest.php" line="17" assertions="0" time="0.013636">
          <error type="CodeIgniter\Database\Exceptions\DatabaseException">ExampleDatabaseTest::testModelFindAll
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [SQLite3]: Class 'SQLite3' not found

/var/www/html/ardis/system/Database/BaseConnection.php:407
/var/www/html/ardis/system/Test/DatabaseTestTrait.php:74
/var/www/html/ardis/system/Test/DatabaseTestTrait.php:54
/var/www/html/ardis/system/Test/CIUnitTestCase.php:244</error>
        </testcase>
        <testcase name="testSoftDeleteLeavesRow" class="ExampleDatabaseTest" classname="ExampleDatabaseTest" file="/var/www/html/ardis/tests/database/ExampleDatabaseTest.php" line="28" assertions="0" time="0.000533">
          <error type="CodeIgniter\Database\Exceptions\DatabaseException">ExampleDatabaseTest::testSoftDeleteLeavesRow
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [SQLite3]: Class 'SQLite3' not found

/var/www/html/ardis/system/Database/BaseConnection.php:407
/var/www/html/ardis/system/Test/DatabaseTestTrait.php:74
/var/www/html/ardis/system/Test/DatabaseTestTrait.php:54
/var/www/html/ardis/system/Test/CIUnitTestCase.php:244</error>
        </testcase>
      </testsuite>
      <testsuite name="ExampleSessionTest" file="/var/www/html/ardis/tests/session/ExampleSessionTest.php" tests="1" assertions="1" errors="0" warnings="0" failures="0" skipped="0" time="0.000529">
        <testcase name="testSessionSimple" class="ExampleSessionTest" classname="ExampleSessionTest" file="/var/www/html/ardis/tests/session/ExampleSessionTest.php" line="11" assertions="1" time="0.000529"/>
      </testsuite>
      <testsuite name="HealthTest" file="/var/www/html/ardis/tests/unit/HealthTest.php" tests="2" assertions="3" errors="0" warnings="0" failures="0" skipped="0" time="0.002787">
        <testcase name="testIsDefinedAppPath" class="HealthTest" classname="HealthTest" file="/var/www/html/ardis/tests/unit/HealthTest.php" line="13" assertions="1" time="0.000366"/>
        <testcase name="testBaseUrlHasBeenSet" class="HealthTest" classname="HealthTest" file="/var/www/html/ardis/tests/unit/HealthTest.php" line="18" assertions="2" time="0.002421"/>
      </testsuite>
    </testsuite>
    <testsuite name="myTest" tests="1" assertions="0" errors="0" warnings="1" failures="0" skipped="0" time="0.000145">
      <testsuite name="App\TestCustomers" file="/var/www/html/ardis/tests/app/Controllers/TestCustomers.php" tests="1" assertions="0" errors="0" warnings="1" failures="0" skipped="0" time="0.000145">
        <testcase name="Warning" assertions="0" time="0.000145">
          <warning type="PHPUnit\Framework\Warning">Warning
No tests found in class "App\TestCustomers".</warning>
        </testcase>
      </testsuite>
    </testsuite>
  </testsuite>
</testsuites>
